import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/layout/Navbar';
import { Sidebar } from '@/components/layout/Sidebar';
import { useAppStore } from '@/lib/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'EduAI Hub - AI-Powered Education Platform',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>  {/* Wrap with QueryClientProvider, etc. */}
          <Navbar />
          <div className="flex pt-16">
            <Sidebar />
            <main className="flex-1 min-h-[calc(100vh-4rem)] p-6 lg:p-8 overflow-auto">
              <div className="max-w-7xl mx-auto transition-opacity duration-150">
                {children}
              </div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}

// Providers component for client-side wrappers
'use client';

import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

const queryClient = new QueryClient();

function Providers({ children }: { children: React.ReactNode }) {
  return <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>;
}
